// Reusable easy question bank for the Lithuania booth quiz.
// The structure is designed so a single quiz page can mix text, flag,
// symbol, and image-led rounds without rewriting the content later.

const QUIZ_VISUALS = {
  lt_flag: {
    kind: "flag",
    label: "Lithuania flag",
    description: "Horizontal stripes: yellow, green, red.",
  },
  myanmar_flag: {
    kind: "flag",
    label: "Myanmar flag",
    description: "Horizontal stripes: yellow, green, red with a large white star.",
  },
  colombia_flag: {
    kind: "flag",
    label: "Colombia flag",
    description: "Horizontal stripes: wide yellow, blue, red.",
  },
  ethiopia_flag: {
    kind: "flag",
    label: "Ethiopia flag",
    description: "Horizontal stripes: green, yellow, red with a blue emblem.",
  },
  germany_flag: {
    kind: "flag",
    label: "Germany flag",
    description: "Horizontal stripes: black, red, gold.",
  },
  latvia_flag: {
    kind: "flag",
    label: "Latvia flag",
    description: "Dark red, white, dark red.",
  },
  estonia_flag: {
    kind: "flag",
    label: "Estonia flag",
    description: "Horizontal stripes: blue, black, white.",
  },
  poland_flag: {
    kind: "flag",
    label: "Poland flag",
    description: "Horizontal stripes: white, red.",
  },
  white_stork: {
    kind: "symbol",
    label: "White stork",
    description: "Large white bird with black wing edges and long red legs.",
  },
  vytis: {
    kind: "symbol",
    label: "Vytis",
    description: "White knight on horseback from Lithuania's coat of arms.",
  },
  amber: {
    kind: "symbol",
    label: "Baltic amber",
    description: "Golden fossil resin often called Lithuanian gold.",
  },
  basketball: {
    kind: "symbol",
    label: "Basketball",
    description: "Orange ball used to represent Lithuania's favorite sport.",
  },
  gediminas_tower: {
    kind: "landmark",
    label: "Gediminas Tower",
    description: "Historic red-brick tower in Vilnius on a hill.",
  },
  trakai_castle: {
    kind: "landmark",
    label: "Trakai Castle",
    description: "Red island castle surrounded by water.",
  },
  hill_of_crosses: {
    kind: "landmark",
    label: "Hill of Crosses",
    description: "Large hill covered with many crosses.",
  },
  cepelinai: {
    kind: "food",
    label: "Cepelinai",
    description: "Big potato dumplings, usually with meat inside.",
  },
  saltibarsciai: {
    kind: "food",
    label: "Saltibarsciai",
    description: "Bright pink cold beet soup.",
  },
  acorn_oak: {
    kind: "nature",
    label: "Oak and acorn",
    description: "Oak tree leaves and acorns, common in Baltic nature themes.",
  },
};

const EASY_QUIZ_QUESTION_BANK = [
  {
    id: "easy-capital-1",
    type: "text",
    topic: "Capital",
    prompt: "What is the capital of Lithuania?",
    options: ["Vilnius", "Kaunas", "Riga", "Tallinn"],
    answerIndex: 0,
    explain: "Vilnius is the capital and biggest city of Lithuania.",
  },
  {
    id: "easy-country-1",
    type: "text",
    topic: "Country",
    prompt: "Which country is this quiz about?",
    options: ["Lithuania", "Latvia", "Poland", "Finland"],
    answerIndex: 0,
    explain: "The booth and quiz are about Lithuania.",
  },
  {
    id: "easy-language-1",
    type: "text",
    topic: "Language",
    prompt: "What language do people speak in Lithuania?",
    options: ["Lithuanian", "Latvian", "German", "Swedish"],
    answerIndex: 0,
    explain: "People in Lithuania speak Lithuanian.",
  },
  {
    id: "easy-sea-1",
    type: "text",
    topic: "Geography",
    prompt: "Lithuania is next to which sea?",
    options: ["Baltic Sea", "Black Sea", "North Sea", "Mediterranean Sea"],
    answerIndex: 0,
    explain: "Lithuania has a Baltic Sea coast.",
  },
  {
    id: "easy-sport-1",
    type: "text",
    topic: "Sport",
    prompt: "Which sport is very popular in Lithuania?",
    options: ["Basketball", "Baseball", "Cricket", "Surfing"],
    answerIndex: 0,
    explain: "Basketball is one of the strongest national symbols in Lithuanian sport.",
  },
  {
    id: "easy-currency-1",
    type: "text",
    topic: "Currency",
    prompt: "What money does Lithuania use today?",
    options: ["Euro", "Dollar", "Pound", "Yen"],
    answerIndex: 0,
    explain: "Lithuania uses the euro.",
  },
  {
    id: "easy-food-1",
    type: "text",
    topic: "Food",
    prompt: "Which one is a famous Lithuanian potato dumpling?",
    options: ["Cepelinai", "Sushi", "Taco", "Croissant"],
    answerIndex: 0,
    explain: "Cepelinai are large potato dumplings and a well-known Lithuanian dish.",
  },
  {
    id: "easy-food-2",
    type: "text",
    topic: "Food",
    prompt: "Which Lithuanian soup is famous for being bright pink?",
    options: ["Saltibarsciai", "Tom yum", "Miso", "Minestrone"],
    answerIndex: 0,
    explain: "Saltibarsciai is a cold pink beet soup.",
  },
  {
    id: "easy-symbol-1",
    type: "text",
    topic: "Symbol",
    prompt: "What is Vytis?",
    options: [
      "A knight on horseback",
      "A type of soup",
      "A Lithuanian river",
      "A basketball team",
    ],
    answerIndex: 0,
    explain: "Vytis is the knight shown on Lithuania's coat of arms.",
  },
  {
    id: "easy-hello-1",
    type: "text",
    topic: "Language",
    prompt: "Which word means hello in Lithuanian?",
    options: ["Labas", "Bonjour", "Ciao", "Aloha"],
    answerIndex: 0,
    explain: "Labas is a common Lithuanian greeting.",
  },
  {
    id: "flag-basic-1",
    type: "flag-pick",
    topic: "Flag",
    prompt: "Pick the flag of Lithuania.",
    optionVisualKeys: ["lt_flag", "latvia_flag", "estonia_flag", "poland_flag"],
    answerIndex: 0,
    explain: "Lithuania's flag is yellow, green, and red.",
  },
  {
    id: "flag-similar-1",
    type: "flag-pick",
    topic: "Flag",
    prompt: "Which flag is Lithuania and not Myanmar?",
    optionVisualKeys: ["myanmar_flag", "lt_flag", "germany_flag", "poland_flag"],
    answerIndex: 1,
    explain: "Myanmar also has yellow, green, and red, but it has a large white star.",
  },
  {
    id: "flag-similar-2",
    type: "flag-pick",
    topic: "Flag",
    prompt: "Which one is the Lithuanian flag and not Colombia?",
    optionVisualKeys: ["colombia_flag", "lt_flag", "latvia_flag", "ethiopia_flag"],
    answerIndex: 1,
    explain: "Colombia has yellow, blue, and red. Lithuania has yellow, green, and red.",
  },
  {
    id: "flag-similar-3",
    type: "flag-pick",
    topic: "Flag",
    prompt: "Choose Lithuania's flag, not Ethiopia's flag.",
    optionVisualKeys: ["ethiopia_flag", "germany_flag", "lt_flag", "myanmar_flag"],
    answerIndex: 2,
    explain: "Ethiopia often includes a blue emblem. Lithuania's flag has only three horizontal stripes.",
  },
  {
    id: "flag-similar-4",
    type: "flag-pick",
    topic: "Flag",
    prompt: "Which flag belongs on the Lithuania booth?",
    optionVisualKeys: ["germany_flag", "lt_flag", "colombia_flag", "latvia_flag"],
    answerIndex: 1,
    explain: "Lithuania's national flag is yellow, green, and red.",
  },
  {
    id: "flag-color-order-1",
    type: "text",
    topic: "Flag",
    prompt: "What are the flag colors of Lithuania from top to bottom?",
    options: [
      "Yellow, green, red",
      "Green, yellow, red",
      "Yellow, red, green",
      "Black, red, gold",
    ],
    answerIndex: 0,
    explain: "The order is yellow on top, green in the middle, red on the bottom.",
  },
  {
    id: "flag-neighbor-1",
    type: "flag-pick",
    topic: "Flag",
    prompt: "Tap Lithuania's flag, not Latvia's flag.",
    optionVisualKeys: ["latvia_flag", "lt_flag", "poland_flag", "estonia_flag"],
    answerIndex: 1,
    explain: "Latvia's flag is dark red and white. Lithuania's is yellow, green, and red.",
  },
  {
    id: "image-symbol-1",
    type: "image-pick",
    topic: "National symbol",
    prompt: "Which image shows the national bird of Lithuania?",
    optionVisualKeys: ["white_stork", "amber", "basketball", "acorn_oak"],
    answerIndex: 0,
    explain: "The white stork is the national bird of Lithuania.",
  },
  {
    id: "image-symbol-2",
    type: "image-pick",
    topic: "National symbol",
    prompt: "Which image shows Vytis?",
    optionVisualKeys: ["gediminas_tower", "vytis", "white_stork", "amber"],
    answerIndex: 1,
    explain: "Vytis is the knight on horseback on Lithuania's coat of arms.",
  },
  {
    id: "image-symbol-3",
    type: "image-pick",
    topic: "National symbol",
    prompt: "Which image shows Baltic amber?",
    optionVisualKeys: ["basketball", "amber", "white_stork", "trakai_castle"],
    answerIndex: 1,
    explain: "Amber is one of Lithuania's best-known natural symbols.",
  },
  {
    id: "image-symbol-4",
    type: "image-pick",
    topic: "Sport",
    prompt: "Which picture matches Lithuania's favorite sport?",
    optionVisualKeys: ["basketball", "white_stork", "amber", "acorn_oak"],
    answerIndex: 0,
    explain: "Basketball is a great easy symbol for Lithuania in booth games.",
  },
  {
    id: "image-landmark-1",
    type: "image-pick",
    topic: "Landmark",
    prompt: "Which image shows Trakai Castle?",
    optionVisualKeys: ["trakai_castle", "hill_of_crosses", "amber", "white_stork"],
    answerIndex: 0,
    explain: "Trakai Castle is the red island castle surrounded by water.",
  },
  {
    id: "image-landmark-2",
    type: "image-pick",
    topic: "Landmark",
    prompt: "Which image shows the Hill of Crosses?",
    optionVisualKeys: ["gediminas_tower", "white_stork", "hill_of_crosses", "cepelinai"],
    answerIndex: 2,
    explain: "The Hill of Crosses is a famous site filled with many crosses.",
  },
  {
    id: "image-landmark-3",
    type: "image-pick",
    topic: "Landmark",
    prompt: "Which image shows a famous tower in Vilnius?",
    optionVisualKeys: ["saltibarsciai", "gediminas_tower", "amber", "basketball"],
    answerIndex: 1,
    explain: "Gediminas Tower is one of the most recognizable Vilnius landmarks.",
  },
  {
    id: "image-food-1",
    type: "image-pick",
    topic: "Food",
    prompt: "Which image shows cepelinai?",
    optionVisualKeys: ["cepelinai", "saltibarsciai", "amber", "white_stork"],
    answerIndex: 0,
    explain: "Cepelinai are large potato dumplings.",
  },
  {
    id: "image-food-2",
    type: "image-pick",
    topic: "Food",
    prompt: "Which image shows the pink Lithuanian soup?",
    optionVisualKeys: ["amber", "saltibarsciai", "acorn_oak", "vytis"],
    answerIndex: 1,
    explain: "Saltibarsciai is the bright pink soup.",
  },
  {
    id: "easy-truefalse-1",
    type: "true-false",
    topic: "Geography",
    prompt: "True or false: Lithuania is in Europe.",
    options: ["True", "False"],
    answerIndex: 0,
    explain: "Lithuania is a European country in the Baltic region.",
  },
  {
    id: "easy-truefalse-2",
    type: "true-false",
    topic: "Flag",
    prompt: "True or false: Lithuania's flag has blue in it.",
    options: ["True", "False"],
    answerIndex: 1,
    explain: "Lithuania's flag uses yellow, green, and red.",
  },
  {
    id: "easy-truefalse-3",
    type: "true-false",
    topic: "Sport",
    prompt: "True or false: Basketball is popular in Lithuania.",
    options: ["True", "False"],
    answerIndex: 0,
    explain: "Basketball is one of the easiest Lithuania facts for visitors to remember.",
  },
  {
    id: "easy-truefalse-4",
    type: "true-false",
    topic: "Food",
    prompt: "True or false: Cepelinai is a Lithuanian dish.",
    options: ["True", "False"],
    answerIndex: 0,
    explain: "Cepelinai is a famous Lithuanian food.",
  },
  {
    id: "easy-match-1",
    type: "text",
    topic: "Identity",
    prompt: "Which city belongs to Lithuania?",
    options: ["Vilnius", "Warsaw", "Stockholm", "Oslo"],
    answerIndex: 0,
    explain: "Vilnius is a Lithuanian city. The others are capitals of other countries.",
  },
  {
    id: "easy-match-2",
    type: "text",
    topic: "Region",
    prompt: "Lithuania is one of the Baltic countries together with Latvia and...",
    options: ["Estonia", "Norway", "Ukraine", "Austria"],
    answerIndex: 0,
    explain: "The three Baltic states are Lithuania, Latvia, and Estonia.",
  },
  {
    id: "easy-match-3",
    type: "text",
    topic: "Nature",
    prompt: "Which natural treasure is often called Lithuanian gold?",
    options: ["Amber", "Silver", "Marble", "Coal"],
    answerIndex: 0,
    explain: "Baltic amber is often called Lithuanian gold.",
  },
  {
    id: "easy-match-4",
    type: "text",
    topic: "Symbol",
    prompt: "Which bird is linked with Lithuania?",
    options: ["White stork", "Penguin", "Parrot", "Flamingo"],
    answerIndex: 0,
    explain: "The white stork is the national bird of Lithuania.",
  },
  {
    id: "easy-match-5",
    type: "text",
    topic: "Landmark",
    prompt: "Which place is famous as a castle on an island in Lithuania?",
    options: ["Trakai Castle", "Big Ben", "Colosseum", "Acropolis"],
    answerIndex: 0,
    explain: "Trakai Castle is one of the easiest Lithuanian landmarks to recognize.",
  },
  {
    id: "easy-match-6",
    type: "text",
    topic: "Landmark",
    prompt: "Which place is known for many crosses on one hill?",
    options: ["Hill of Crosses", "Eiffel Tower", "Brandenburg Gate", "Stonehenge"],
    answerIndex: 0,
    explain: "The Hill of Crosses is one of Lithuania's best-known religious landmarks.",
  },
];

if (typeof window !== "undefined") {
  window.QUIZ_VISUALS = QUIZ_VISUALS;
  window.EASY_QUIZ_QUESTION_BANK = EASY_QUIZ_QUESTION_BANK;
}

